### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by jasonhjohnson** [vtfuture/RequireJSDotNet#51]
After getting the latest release the Resolve method no longer finds my controller js files. It looks like the ".js" portion is missing from the reference. 

I downloaded the source and modified the lines that looked like this:
```
return withBaseUrl ? computedEntry : rootUrl + computedEntry;
```

...to look like this:
```
return withBaseUrl ? computedEntry : rootUrl + computedEntry + ".js";
```

...and that seemed to fix it. Though I'm sure that was wrong and probably broke something else.

Thanks,
Jason

**Comment by CezarCretu** [comment]
The entrypoint is not supposed to have the .js termination since it should be a require.js module name. Can you tell me more about how you've configured it and what your file layout is?

**Comment by jasonhjohnson** [comment]
Here's some screenshots that should help:

https://www.dropbox.com/s/1ipebqdzhgvr8am/shot_150203_125148.png?dl=0

https://www.dropbox.com/s/cm4ila1r2vweukc/shot_150203_125229.png?dl=0

https://www.dropbox.com/s/nbs99eyc5218x5u/shot_150203_125257.png?dl=0

Thanks!
Jason

**Comment by CezarCretu** [comment]
That's great, thanks. I'll have a look at it later.

**Comment by jasonhjohnson** [comment]
Any luck fixing this?

**Comment by CezarCretu** [comment]
Could you please:

* Delete any existing ```.override.``` file and re-build (or do whatever it is that triggers the auto-compressor for you) so that we can make sure you have the correct settings in it
* If the problem still persists, set ```RequireRendererConfiguration.LoadOverrides``` to ```false```
* Provide me with the contents of any ```.override.``` file you might have (in the screenshots it looks like there's only one, ```RequireJS.override.json```)
* Provide me with the generated javascript after RequireJs.Net renders it, it should look something like this:

```

<script>var requireConfig = ...</script>
<script src=".../require.js"></script>
<script>require(["modulename"]);</script>

**Comment by afgallo** [comment]
Hi,

This line is what's causing the ".js" file extension bug:

//EntryPointRoot = "~/scripts/", THIS CAUSES A BUG with .js file extension

@jasonhjohnson if you comment that out like I did, there is no need to change the source code.

This might help @CezarCretu diagnose the issue.
Thanks

**Comment by fuzzlebuck** [comment]
I have this same issue, changing 

EntryPointRoot = "~/Scripts/"

To anything other than "~/Scripts" causes the require root to render as a full path, which means that RequireJS think's it's a full URL and does not append the .js.

e.g

require(["/Scripts/Debug/controllers/root/home/index"]);

"~/Scripts/" is hardcoded as a constant in DefaultEntryPointResolver.

Maybe entryPointRoot should be compared against baseUrl rather than a constant?

**Comment by puddlewitt** [comment]
I have the same issue, I followed the recommendation from @afgallo which fixed my issue.
