### ISSUE TITLE
AutoBundle issue - Jint.Parser.Ast.BinaryExpression cast

### ISSUE THREAD

**Issue by delvesoftware** [vtfuture/RequireJSDotNet#54]
Hi, 

Thanks for RequireJSDotNet! It's awesome. When I'm using the auto compressor and building I get the following error:

"Error 59 Unable to cast object of type 'Jint.Parser.Ast.BinaryExpression' to type 'Jint.Parser.Ast.Literal'"

I don't have any complicated defines or requires, they are all just string literals. My project consists of 50+ js files and is fairly complicated so hard to track down which file it is having trouble with.

Any idea what might be causing this issue?

**Comment by fuzzlebuck** [comment]
With a fair amount of logging I discovered the issue is caused when there is an expression in a require() statement. 

The 'RequireVisitor' falls over with the exception in this situation, causing the rest of the process to stop. 

Is there a way to use auto bundles but specify some files to not auto resolve?

You can try replicate the issue by requiring the knockout amd helpers located here:

https://github.com/rniemeyer/knockout-amd-helpers

**Comment by aquamoth** [comment]
I havn't tested the knockout amd helpers explicitly, but in the master branch the compressor now ignores single required expressions. In dependency arrays dynamic dependencies were already supported.
