### ISSUE TITLE
Script file location

### ISSUE THREAD

**Issue by AubieDawg92** [vtfuture/RequireJSDotNet#60]
Is it possible to configure an alternate convention for the script files?  For example, I really only have 1 action in the controller (Index), which would map to Scripts/controllers/root/{controller}/index.js.  Which is ok, except I end up with a ton of files called index.js which can get confusing if you have to open more than one of them at a time.  What I would really like is for the convention to be scripts/{some folder}/{controller}.js or even better scripts/{some folder}/{controller}-view.js.

Is this possible today?  Would that be a custom IEntryPointResolver?  Are those configurable without compiling?

Maybe there could be a simple configuration option that used standardized place holders similar to mvc route configs.

**Comment by johndubya** [comment]
See the documentation on GitHub located here: https://github.com/vtfuture/RequireJSDotNet/wiki/Overriding-entry-point-path-generation

Somewhere in your Controller (probably a BaseController that all your Controllers inherit from, so you don't have to copy this line in every action), you would include code like this:

`RequireJsNet.RequireJsOptions.ResolverCollection.Add(new MySolution.App_Code.RequireJsFallbackEntryPointResolver());`

You can put that `RequireJsFallbackEntryPointResolver` class wherever it needs to go in your project. Then, take a look at the [`DefaultEntryPointResolver`](https://github.com/vtfuture/RequireJSDotNet/blob/master/RequireJsNet/EntryPointResolver/DefaultEntryPointResolver.cs) for hints in how to setup your path conventions. You can either leave the `DefaultEntryPointResolver` in the `RequireJsOptions.ResolverCollection` and have yours run after it, or you could run `RequireJsOptions.ResolverCollection.Clear()` before running the `Add()` as seen in my example above.

I just had to figure all this out on my own a little bit ago, since the documentation isn't clear at all on this, so hopefully this helps others as well.
