### ISSUE TITLE
Data-Main entry point for main/global js

### ISSUE THREAD

**Issue by brunobertechini** [vtfuture/RequireJSDotNet#63]
Hello,

Is here something related to the data-main atribute from requirejs ?

I would like to load certain scripts every time (for all pages) without the need to do a requirejs(['core']) for example

Is that possible today ?

Bruno

**Comment by CezarCretu** [comment]
> Is here something related to the data-main atribute from requirejs ?

I'm not sure I understand what you're asking here. We actually don't use the ```data-main``` attribute when generating the script tag and have replaced it with ```<script>require(['your-module'])</script>```, achieving the single entry point intention of ```data-main```. Is there any specific scenario that's enabled in require.js and not in RequireJsDotNet?

Regarding your second point, my personal preference would be to list dependencies explicitly (if they are actually required in your current module) and otherwise let the dependency tree take care of things.

**Comment by brunobertechini** [comment]
I agree with you.

I was just comparing with the data-main from OOB requirejs.

Bruno
